### ISSUE TITLE
Figure 2.1.2 doesn't render

### ISSUE THREAD

**Issue by es50678** [klevasseur/ads#11]
### Browser info:
Chrome Version 90.0.4430.212 (Official Build) (x86_64)

![2021-05-29 12 10 19](https://user-images.githubusercontent.com/17823824/120077150-f2603f80-c076-11eb-934b-dc270695c0bf.gif)

**Comment by es50678** [comment]
Quick update: looks like it was my adblocker for some reason. Just disabled it on the page and the images are now loading. Not sure why the ad-blocker would block images from the same origin.

**Comment by ValZapod** [comment]
That is either because ads is the name of the site or it is loaded from some script that is blocked, there are some eTLD+1 warnings.

**Comment by klevasseur** [comment]
Hello.

I’ve gotten this report and it seems that it’s an issue with adblockers. If you disable them on your browser, it should fix the problem. 

Ken Levasseur
http://kenlevasseur.org
